// AUTOMATICALLY GENERATED BY OPENFEATURE CLI, DO NOT EDIT.
package openfeature

import (
	"context"
	"fmt"
	"github.com/open-feature/go-sdk/openfeature"
)

// stringer transforms a string to a Stringer
type stringer string

// String implements the fmt.Stringer interface
func (s stringer) String() string {
	return string(s)
}

type BooleanProvider func(ctx context.Context, evalCtx openfeature.EvaluationContext) (bool, error)
type BooleanProviderDetails func(ctx context.Context, evalCtx openfeature.EvaluationContext) (openfeature.BooleanEvaluationDetails, error)
type FloatProvider func(ctx context.Context, evalCtx openfeature.EvaluationContext) (float64, error)
type FloatProviderDetails func(ctx context.Context, evalCtx openfeature.EvaluationContext) (openfeature.FloatEvaluationDetails, error)
type IntProvider func(ctx context.Context, evalCtx openfeature.EvaluationContext) (int64, error)
type IntProviderDetails func(ctx context.Context, evalCtx openfeature.EvaluationContext) (openfeature.IntEvaluationDetails, error)
type StringProvider func(ctx context.Context, evalCtx openfeature.EvaluationContext) (string, error)
type StringProviderDetails func(ctx context.Context, evalCtx openfeature.EvaluationContext) (openfeature.StringEvaluationDetails, error)
type ObjectProvider func(ctx context.Context, evalCtx openfeature.EvaluationContext) (any, error)
type ObjectProviderDetails func(ctx context.Context, evalCtx openfeature.EvaluationContext) (openfeature.InterfaceEvaluationDetails, error)

var client openfeature.IClient = nil
// Discount percentage applied to purchases.
var DiscountPercentage = struct {
    fmt.Stringer
    // Value returns the value of the flag DiscountPercentage,
    // as well as the evaluation error, if present.
    Value FloatProvider

    // ValueWithDetails returns the value of the flag DiscountPercentage,
    // the evaluation error, if any, and the evaluation details.
    ValueWithDetails FloatProviderDetails
}{
    Stringer: stringer("discountPercentage"),
    Value: func(ctx context.Context, evalCtx openfeature.EvaluationContext) (float64, error) {
        return client.FloatValue(ctx, "discountPercentage", 0.15, evalCtx)
    },
    ValueWithDetails: func(ctx context.Context, evalCtx openfeature.EvaluationContext) (openfeature.FloatEvaluationDetails, error){
        return client.FloatValueDetails(ctx, "discountPercentage", 0.15, evalCtx)
    },
}
// Controls whether Feature A is enabled.
var EnableFeatureA = struct {
    fmt.Stringer
    // Value returns the value of the flag EnableFeatureA,
    // as well as the evaluation error, if present.
    Value BooleanProvider

    // ValueWithDetails returns the value of the flag EnableFeatureA,
    // the evaluation error, if any, and the evaluation details.
    ValueWithDetails BooleanProviderDetails
}{
    Stringer: stringer("enableFeatureA"),
    Value: func(ctx context.Context, evalCtx openfeature.EvaluationContext) (bool, error) {
        return client.BooleanValue(ctx, "enableFeatureA", false, evalCtx)
    },
    ValueWithDetails: func(ctx context.Context, evalCtx openfeature.EvaluationContext) (openfeature.BooleanEvaluationDetails, error){
        return client.BooleanValueDetails(ctx, "enableFeatureA", false, evalCtx)
    },
}
// The message to use for greeting users.
var GreetingMessage = struct {
    fmt.Stringer
    // Value returns the value of the flag GreetingMessage,
    // as well as the evaluation error, if present.
    Value StringProvider

    // ValueWithDetails returns the value of the flag GreetingMessage,
    // the evaluation error, if any, and the evaluation details.
    ValueWithDetails StringProviderDetails
}{
    Stringer: stringer("greetingMessage"),
    Value: func(ctx context.Context, evalCtx openfeature.EvaluationContext) (string, error) {
        return client.StringValue(ctx, "greetingMessage", "Hello there!", evalCtx)
    },
    ValueWithDetails: func(ctx context.Context, evalCtx openfeature.EvaluationContext) (openfeature.StringEvaluationDetails, error){
        return client.StringValueDetails(ctx, "greetingMessage", "Hello there!", evalCtx)
    },
}
// Allows customization of theme colors.
var ThemeCustomization = struct {
    fmt.Stringer
    // Value returns the value of the flag ThemeCustomization,
    // as well as the evaluation error, if present.
    Value ObjectProvider

    // ValueWithDetails returns the value of the flag ThemeCustomization,
    // the evaluation error, if any, and the evaluation details.
    ValueWithDetails ObjectProviderDetails
}{
    Stringer: stringer("themeCustomization"),
    Value: func(ctx context.Context, evalCtx openfeature.EvaluationContext) (any, error) {
        return client.ObjectValue(ctx, "themeCustomization", map[string]any{"primaryColor": "#007bff", "secondaryColor": "#6c757d"}, evalCtx)
    },
    ValueWithDetails: func(ctx context.Context, evalCtx openfeature.EvaluationContext) (openfeature.InterfaceEvaluationDetails, error){
        return client.ObjectValueDetails(ctx, "themeCustomization", map[string]any{"primaryColor": "#007bff", "secondaryColor": "#6c757d"}, evalCtx)
    },
}
// Maximum allowed length for usernames.
var UsernameMaxLength = struct {
    fmt.Stringer
    // Value returns the value of the flag UsernameMaxLength,
    // as well as the evaluation error, if present.
    Value IntProvider

    // ValueWithDetails returns the value of the flag UsernameMaxLength,
    // the evaluation error, if any, and the evaluation details.
    ValueWithDetails IntProviderDetails
}{
    Stringer: stringer("usernameMaxLength"),
    Value: func(ctx context.Context, evalCtx openfeature.EvaluationContext) (int64, error) {
        return client.IntValue(ctx, "usernameMaxLength", 50, evalCtx)
    },
    ValueWithDetails: func(ctx context.Context, evalCtx openfeature.EvaluationContext) (openfeature.IntEvaluationDetails, error){
        return client.IntValueDetails(ctx, "usernameMaxLength", 50, evalCtx)
    },
}

func init() {
    client = openfeature.GetApiInstance().GetClient()
}
