// Package pushclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package pushclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for FlagType.
const (
	Boolean FlagType = "boolean"
	Float   FlagType = "float"
	Integer FlagType = "integer"
	Object  FlagType = "object"
	String  FlagType = "string"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Error code for programmatic handling
	Code *string `json:"code,omitempty"`

	// Error Error message
	Error string `json:"error"`
}

// Flag defines model for Flag.
type Flag struct {
	// DefaultValue Default value returned when flag evaluation fails
	DefaultValue interface{} `json:"defaultValue"`

	// Description Human-readable description of the flag's purpose
	Description *string `json:"description,omitempty"`

	// Key Unique identifier for the feature flag
	Key string `json:"key"`

	// Type Data type of the flag value
	Type FlagType `json:"type"`
}

// FlagType Data type of the flag value
type FlagType string

// FlagPayload defines model for FlagPayload.
type FlagPayload struct {
	// Schema JSON schema reference for validation
	Schema *string `json:"$schema,omitempty"`

	// Flags Array of feature flag configurations
	Flags []Flag `json:"flags"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	// Count Number of flags processed
	Count int `json:"count"`

	// Flags List of flag keys that were processed
	Flags   *[]string `json:"flags,omitempty"`
	Message string    `json:"message"`
}

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse struct {
	// Error General error message
	Error      string                `json:"error"`
	Violations []ValidationViolation `json:"violations"`
}

// ValidationViolation defines model for ValidationViolation.
type ValidationViolation struct {
	// Field Field path that failed validation
	Field string `json:"field"`

	// Message Validation error message
	Message string `json:"message"`

	// Value The invalid value that was provided
	Value interface{} `json:"value,omitempty"`
}

// PushFlagsJSONRequestBody defines body for PushFlags for application/json ContentType.
type PushFlagsJSONRequestBody = FlagPayload

// ReplaceFlagsJSONRequestBody defines body for ReplaceFlags for application/json ContentType.
type ReplaceFlagsJSONRequestBody = FlagPayload

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PushFlagsWithBody request with any body
	PushFlagsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PushFlags(ctx context.Context, body PushFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReplaceFlagsWithBody request with any body
	ReplaceFlagsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ReplaceFlags(ctx context.Context, body ReplaceFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PushFlagsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPushFlagsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PushFlags(ctx context.Context, body PushFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPushFlagsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReplaceFlagsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceFlagsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReplaceFlags(ctx context.Context, body ReplaceFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceFlagsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPushFlagsRequest calls the generic PushFlags builder with application/json body
func NewPushFlagsRequest(server string, body PushFlagsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPushFlagsRequestWithBody(server, "application/json", bodyReader)
}

// NewPushFlagsRequestWithBody generates requests for PushFlags with any type of body
func NewPushFlagsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/flags")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewReplaceFlagsRequest calls the generic ReplaceFlags builder with application/json body
func NewReplaceFlagsRequest(server string, body ReplaceFlagsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReplaceFlagsRequestWithBody(server, "application/json", bodyReader)
}

// NewReplaceFlagsRequestWithBody generates requests for ReplaceFlags with any type of body
func NewReplaceFlagsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/flags")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PushFlagsWithBodyWithResponse request with any body
	PushFlagsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushFlagsResponse, error)

	PushFlagsWithResponse(ctx context.Context, body PushFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*PushFlagsResponse, error)

	// ReplaceFlagsWithBodyWithResponse request with any body
	ReplaceFlagsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReplaceFlagsResponse, error)

	ReplaceFlagsWithResponse(ctx context.Context, body ReplaceFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*ReplaceFlagsResponse, error)
}

type PushFlagsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SuccessResponse
	JSON201      *SuccessResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON422      *ValidationErrorResponse
}

// Status returns HTTPResponse.Status
func (r PushFlagsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PushFlagsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ReplaceFlagsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SuccessResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON422      *ValidationErrorResponse
}

// Status returns HTTPResponse.Status
func (r ReplaceFlagsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReplaceFlagsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PushFlagsWithBodyWithResponse request with arbitrary body returning *PushFlagsResponse
func (c *ClientWithResponses) PushFlagsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushFlagsResponse, error) {
	rsp, err := c.PushFlagsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePushFlagsResponse(rsp)
}

func (c *ClientWithResponses) PushFlagsWithResponse(ctx context.Context, body PushFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*PushFlagsResponse, error) {
	rsp, err := c.PushFlags(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePushFlagsResponse(rsp)
}

// ReplaceFlagsWithBodyWithResponse request with arbitrary body returning *ReplaceFlagsResponse
func (c *ClientWithResponses) ReplaceFlagsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReplaceFlagsResponse, error) {
	rsp, err := c.ReplaceFlagsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReplaceFlagsResponse(rsp)
}

func (c *ClientWithResponses) ReplaceFlagsWithResponse(ctx context.Context, body ReplaceFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*ReplaceFlagsResponse, error) {
	rsp, err := c.ReplaceFlags(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReplaceFlagsResponse(rsp)
}

// ParsePushFlagsResponse parses an HTTP response from a PushFlagsWithResponse call
func ParsePushFlagsResponse(rsp *http.Response) (*PushFlagsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PushFlagsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SuccessResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest SuccessResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ValidationErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseReplaceFlagsResponse parses an HTTP response from a ReplaceFlagsWithResponse call
func ParseReplaceFlagsResponse(rsp *http.Response) (*ReplaceFlagsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReplaceFlagsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SuccessResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ValidationErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}
