// Package syncclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package syncclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ManifestFlagType.
const (
	ManifestFlagTypeBoolean ManifestFlagType = "boolean"
	ManifestFlagTypeInteger ManifestFlagType = "integer"
	ManifestFlagTypeObject  ManifestFlagType = "object"
	ManifestFlagTypeString  ManifestFlagType = "string"
)

// Valid indicates whether the value is a known member of the ManifestFlagType enum.
func (e ManifestFlagType) Valid() bool {
	switch e {
	case ManifestFlagTypeBoolean:
		return true
	case ManifestFlagTypeInteger:
		return true
	case ManifestFlagTypeObject:
		return true
	case ManifestFlagTypeString:
		return true
	default:
		return false
	}
}

// Defines values for PostOpenfeatureV0ManifestFlagsJSONBodyType.
const (
	PostOpenfeatureV0ManifestFlagsJSONBodyTypeBoolean PostOpenfeatureV0ManifestFlagsJSONBodyType = "boolean"
	PostOpenfeatureV0ManifestFlagsJSONBodyTypeInteger PostOpenfeatureV0ManifestFlagsJSONBodyType = "integer"
	PostOpenfeatureV0ManifestFlagsJSONBodyTypeObject  PostOpenfeatureV0ManifestFlagsJSONBodyType = "object"
	PostOpenfeatureV0ManifestFlagsJSONBodyTypeString  PostOpenfeatureV0ManifestFlagsJSONBodyType = "string"
)

// Valid indicates whether the value is a known member of the PostOpenfeatureV0ManifestFlagsJSONBodyType enum.
func (e PostOpenfeatureV0ManifestFlagsJSONBodyType) Valid() bool {
	switch e {
	case PostOpenfeatureV0ManifestFlagsJSONBodyTypeBoolean:
		return true
	case PostOpenfeatureV0ManifestFlagsJSONBodyTypeInteger:
		return true
	case PostOpenfeatureV0ManifestFlagsJSONBodyTypeObject:
		return true
	case PostOpenfeatureV0ManifestFlagsJSONBodyTypeString:
		return true
	default:
		return false
	}
}

// Defines values for PutOpenfeatureV0ManifestFlagsKeyJSONBodyType.
const (
	PutOpenfeatureV0ManifestFlagsKeyJSONBodyTypeBoolean PutOpenfeatureV0ManifestFlagsKeyJSONBodyType = "boolean"
	PutOpenfeatureV0ManifestFlagsKeyJSONBodyTypeInteger PutOpenfeatureV0ManifestFlagsKeyJSONBodyType = "integer"
	PutOpenfeatureV0ManifestFlagsKeyJSONBodyTypeObject  PutOpenfeatureV0ManifestFlagsKeyJSONBodyType = "object"
	PutOpenfeatureV0ManifestFlagsKeyJSONBodyTypeString  PutOpenfeatureV0ManifestFlagsKeyJSONBodyType = "string"
)

// Valid indicates whether the value is a known member of the PutOpenfeatureV0ManifestFlagsKeyJSONBodyType enum.
func (e PutOpenfeatureV0ManifestFlagsKeyJSONBodyType) Valid() bool {
	switch e {
	case PutOpenfeatureV0ManifestFlagsKeyJSONBodyTypeBoolean:
		return true
	case PutOpenfeatureV0ManifestFlagsKeyJSONBodyTypeInteger:
		return true
	case PutOpenfeatureV0ManifestFlagsKeyJSONBodyTypeObject:
		return true
	case PutOpenfeatureV0ManifestFlagsKeyJSONBodyTypeString:
		return true
	default:
		return false
	}
}

// ArchiveResponse defines model for ArchiveResponse.
type ArchiveResponse struct {
	// ArchivedAt Timestamp recording when the flag was archived.
	ArchivedAt *time.Time `json:"archivedAt"`

	// Message Example: Flag "search-rollout" archived. Restore it using your management interface if needed.
	Message string `json:"message"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Code Short machine-readable code (matches Zod issue codes).
	//
	// Example: invalid_type
	Code *string `json:"code,omitempty"`

	// Field Field path related to the error.
	//
	// Example: key
	Field *string `json:"field,omitempty"`

	// Message Human-friendly error message.
	//
	// Example: Flag exists but is archived. Restore it via the UI to reuse this key.
	Message *string `json:"message,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Details *[]ErrorDetail `json:"details,omitempty"`

		// Message Example: Flag type cannot be changed from boolean to string.
		Message string `json:"message"`

		// Status Example: 409
		Status int `json:"status"`
	} `json:"error"`
}

// FlagDefaultValue Default value for a flag (can be boolean, string, integer, or object)
type FlagDefaultValue struct {
	union json.RawMessage
}

// FlagDefaultValue0 defines model for FlagDefaultValue.0.
type FlagDefaultValue0 = bool

// FlagDefaultValue1 defines model for FlagDefaultValue.1.
type FlagDefaultValue1 = string

// FlagDefaultValue2 defines model for FlagDefaultValue.2.
type FlagDefaultValue2 = int

// FlagDefaultValue3 defines model for FlagDefaultValue.3.
type FlagDefaultValue3 = map[string]interface{}

// ManifestEnvelope defines model for ManifestEnvelope.
type ManifestEnvelope struct {
	Flags []ManifestFlag `json:"flags"`
}

// ManifestFlag defines model for ManifestFlag.
type ManifestFlag struct {
	// DefaultValue Default value for a flag (can be boolean, string, integer, or object)
	DefaultValue FlagDefaultValue `json:"defaultValue"`

	// Description Optional flag description.
	//
	// Example: Enable the new search experience.
	Description *string `json:"description,omitempty"`

	// Key Unique flag key within the flag set.
	//
	// Example: search-rollout
	Key string `json:"key"`

	// Name Human-friendly flag name. Defaults to the key when omitted.
	//
	// Example: Search rollout
	Name *string `json:"name,omitempty"`

	// Type Flag data type.
	Type ManifestFlagType `json:"type"`
}

// ManifestFlagType Flag data type.
type ManifestFlagType string

// ManifestFlagResponse defines model for ManifestFlagResponse.
type ManifestFlagResponse struct {
	Flag ManifestFlag `json:"flag"`

	// UpdatedAt ISO timestamp reflecting the last update to the flag record. Clients can use this to
	// detect changes between manifest fetches or to implement optimistic concurrency checks.
	//
	//
	// Example: 2024-03-02T09:45:03.000Z
	UpdatedAt time.Time `json:"updatedAt"`
}

// PostOpenfeatureV0ManifestFlagsJSONBody defines parameters for PostOpenfeatureV0ManifestFlags.
type PostOpenfeatureV0ManifestFlagsJSONBody struct {
	// DefaultValue Default value for a flag (can be boolean, string, integer, or object)
	DefaultValue FlagDefaultValue `json:"defaultValue"`

	// Description Example: Enable the new search experience.
	Description *string `json:"description,omitempty"`

	// Key Example: search-rollout
	Key string `json:"key"`

	// Name Optional display name. Defaults to the key.
	//
	// Example: Search rollout
	Name *string                                    `json:"name,omitempty"`
	Type PostOpenfeatureV0ManifestFlagsJSONBodyType `json:"type"`
}

// PostOpenfeatureV0ManifestFlagsJSONBodyType defines parameters for PostOpenfeatureV0ManifestFlags.
type PostOpenfeatureV0ManifestFlagsJSONBodyType string

// PutOpenfeatureV0ManifestFlagsKeyJSONBody defines parameters for PutOpenfeatureV0ManifestFlagsKey.
type PutOpenfeatureV0ManifestFlagsKeyJSONBody struct {
	// DefaultValue Default value for a flag (can be boolean, string, integer, or object)
	DefaultValue *FlagDefaultValue `json:"defaultValue,omitempty"`
	Description  *string           `json:"description,omitempty"`

	// Key Example: search-rollout
	Key string `json:"key"`

	// Name Example: Search rollout
	Name *string                                      `json:"name,omitempty"`
	Type PutOpenfeatureV0ManifestFlagsKeyJSONBodyType `json:"type"`
}

// PutOpenfeatureV0ManifestFlagsKeyJSONBodyType defines parameters for PutOpenfeatureV0ManifestFlagsKey.
type PutOpenfeatureV0ManifestFlagsKeyJSONBodyType string

// PostOpenfeatureV0ManifestFlagsJSONRequestBody defines body for PostOpenfeatureV0ManifestFlags for application/json ContentType.
type PostOpenfeatureV0ManifestFlagsJSONRequestBody PostOpenfeatureV0ManifestFlagsJSONBody

// PutOpenfeatureV0ManifestFlagsKeyJSONRequestBody defines body for PutOpenfeatureV0ManifestFlagsKey for application/json ContentType.
type PutOpenfeatureV0ManifestFlagsKeyJSONRequestBody PutOpenfeatureV0ManifestFlagsKeyJSONBody

// AsFlagDefaultValue0 returns the union data inside the FlagDefaultValue as a FlagDefaultValue0
func (t FlagDefaultValue) AsFlagDefaultValue0() (FlagDefaultValue0, error) {
	var body FlagDefaultValue0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFlagDefaultValue0 overwrites any union data inside the FlagDefaultValue as the provided FlagDefaultValue0
func (t *FlagDefaultValue) FromFlagDefaultValue0(v FlagDefaultValue0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFlagDefaultValue0 performs a merge with any union data inside the FlagDefaultValue, using the provided FlagDefaultValue0
func (t *FlagDefaultValue) MergeFlagDefaultValue0(v FlagDefaultValue0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFlagDefaultValue1 returns the union data inside the FlagDefaultValue as a FlagDefaultValue1
func (t FlagDefaultValue) AsFlagDefaultValue1() (FlagDefaultValue1, error) {
	var body FlagDefaultValue1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFlagDefaultValue1 overwrites any union data inside the FlagDefaultValue as the provided FlagDefaultValue1
func (t *FlagDefaultValue) FromFlagDefaultValue1(v FlagDefaultValue1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFlagDefaultValue1 performs a merge with any union data inside the FlagDefaultValue, using the provided FlagDefaultValue1
func (t *FlagDefaultValue) MergeFlagDefaultValue1(v FlagDefaultValue1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFlagDefaultValue2 returns the union data inside the FlagDefaultValue as a FlagDefaultValue2
func (t FlagDefaultValue) AsFlagDefaultValue2() (FlagDefaultValue2, error) {
	var body FlagDefaultValue2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFlagDefaultValue2 overwrites any union data inside the FlagDefaultValue as the provided FlagDefaultValue2
func (t *FlagDefaultValue) FromFlagDefaultValue2(v FlagDefaultValue2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFlagDefaultValue2 performs a merge with any union data inside the FlagDefaultValue, using the provided FlagDefaultValue2
func (t *FlagDefaultValue) MergeFlagDefaultValue2(v FlagDefaultValue2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFlagDefaultValue3 returns the union data inside the FlagDefaultValue as a FlagDefaultValue3
func (t FlagDefaultValue) AsFlagDefaultValue3() (FlagDefaultValue3, error) {
	var body FlagDefaultValue3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFlagDefaultValue3 overwrites any union data inside the FlagDefaultValue as the provided FlagDefaultValue3
func (t *FlagDefaultValue) FromFlagDefaultValue3(v FlagDefaultValue3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFlagDefaultValue3 performs a merge with any union data inside the FlagDefaultValue, using the provided FlagDefaultValue3
func (t *FlagDefaultValue) MergeFlagDefaultValue3(v FlagDefaultValue3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t FlagDefaultValue) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *FlagDefaultValue) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetOpenfeatureV0Manifest Get Project Manifest
	//
	// Returns the project manifest containing active flags. Archived flags are excluded.
	// The response includes an `X-Manifest-Capabilities` header listing token capabilities.
	//
	// Corresponds with GET /openfeature/v0/manifest (the `GetOpenfeatureV0Manifest` operationId).
	GetOpenfeatureV0Manifest(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostOpenfeatureV0ManifestFlagsWithBody Create Manifest Flag
	//
	// Creates a new flag exposed through the manifest. The request must be authenticated
	// with a token that includes `write` or `delete` capability. Attempting to create a
	// flag whose key already exists (active or archived) returns 409.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /openfeature/v0/manifest/flags (the `PostOpenfeatureV0ManifestFlags` operationId).
	PostOpenfeatureV0ManifestFlagsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostOpenfeatureV0ManifestFlags Create Manifest Flag
	//
	// Creates a new flag exposed through the manifest. The request must be authenticated
	// with a token that includes `write` or `delete` capability. Attempting to create a
	// flag whose key already exists (active or archived) returns 409.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /openfeature/v0/manifest/flags (the `PostOpenfeatureV0ManifestFlags` operationId).
	PostOpenfeatureV0ManifestFlags(ctx context.Context, body PostOpenfeatureV0ManifestFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteOpenfeatureV0ManifestFlagsKey Archive Manifest Flag
	//
	// Removes a flag from the manifest. Providers may implement this as either a soft
	// delete (archive) or a hard delete; consult your provider documentation for specifics.
	// Flags that are active in protected environments may reject deletion requests depending
	// on provider policy.
	//
	// Corresponds with DELETE /openfeature/v0/manifest/flags/{key} (the `DeleteOpenfeatureV0ManifestFlagsKey` operationId).
	DeleteOpenfeatureV0ManifestFlagsKey(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutOpenfeatureV0ManifestFlagsKeyWithBody Update Manifest Flag
	//
	// Replaces metadata for an existing manifest flag. The path parameter and body key must
	// match. Archived flags cannot be updated; they must be restored before modification.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /openfeature/v0/manifest/flags/{key} (the `PutOpenfeatureV0ManifestFlagsKey` operationId).
	PutOpenfeatureV0ManifestFlagsKeyWithBody(ctx context.Context, key string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutOpenfeatureV0ManifestFlagsKey Update Manifest Flag
	//
	// Replaces metadata for an existing manifest flag. The path parameter and body key must
	// match. Archived flags cannot be updated; they must be restored before modification.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /openfeature/v0/manifest/flags/{key} (the `PutOpenfeatureV0ManifestFlagsKey` operationId).
	PutOpenfeatureV0ManifestFlagsKey(ctx context.Context, key string, body PutOpenfeatureV0ManifestFlagsKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetOpenfeatureV0Manifest Get Project Manifest
//
// Returns the project manifest containing active flags. Archived flags are excluded.
// The response includes an `X-Manifest-Capabilities` header listing token capabilities.
//
// Corresponds with GET /openfeature/v0/manifest (the `GetOpenfeatureV0Manifest` operationId).
func (c *Client) GetOpenfeatureV0Manifest(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOpenfeatureV0ManifestRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostOpenfeatureV0ManifestFlagsWithBody Create Manifest Flag
//
// Creates a new flag exposed through the manifest. The request must be authenticated
// with a token that includes `write` or `delete` capability. Attempting to create a
// flag whose key already exists (active or archived) returns 409.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /openfeature/v0/manifest/flags (the `PostOpenfeatureV0ManifestFlags` operationId).
func (c *Client) PostOpenfeatureV0ManifestFlagsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOpenfeatureV0ManifestFlagsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostOpenfeatureV0ManifestFlags Create Manifest Flag
//
// Creates a new flag exposed through the manifest. The request must be authenticated
// with a token that includes `write` or `delete` capability. Attempting to create a
// flag whose key already exists (active or archived) returns 409.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /openfeature/v0/manifest/flags (the `PostOpenfeatureV0ManifestFlags` operationId).
func (c *Client) PostOpenfeatureV0ManifestFlags(ctx context.Context, body PostOpenfeatureV0ManifestFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOpenfeatureV0ManifestFlagsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteOpenfeatureV0ManifestFlagsKey Archive Manifest Flag
//
// Removes a flag from the manifest. Providers may implement this as either a soft
// delete (archive) or a hard delete; consult your provider documentation for specifics.
// Flags that are active in protected environments may reject deletion requests depending
// on provider policy.
//
// Corresponds with DELETE /openfeature/v0/manifest/flags/{key} (the `DeleteOpenfeatureV0ManifestFlagsKey` operationId).
func (c *Client) DeleteOpenfeatureV0ManifestFlagsKey(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteOpenfeatureV0ManifestFlagsKeyRequest(c.Server, key)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutOpenfeatureV0ManifestFlagsKeyWithBody Update Manifest Flag
//
// Replaces metadata for an existing manifest flag. The path parameter and body key must
// match. Archived flags cannot be updated; they must be restored before modification.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /openfeature/v0/manifest/flags/{key} (the `PutOpenfeatureV0ManifestFlagsKey` operationId).
func (c *Client) PutOpenfeatureV0ManifestFlagsKeyWithBody(ctx context.Context, key string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutOpenfeatureV0ManifestFlagsKeyRequestWithBody(c.Server, key, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutOpenfeatureV0ManifestFlagsKey Update Manifest Flag
//
// Replaces metadata for an existing manifest flag. The path parameter and body key must
// match. Archived flags cannot be updated; they must be restored before modification.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /openfeature/v0/manifest/flags/{key} (the `PutOpenfeatureV0ManifestFlagsKey` operationId).
func (c *Client) PutOpenfeatureV0ManifestFlagsKey(ctx context.Context, key string, body PutOpenfeatureV0ManifestFlagsKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutOpenfeatureV0ManifestFlagsKeyRequest(c.Server, key, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetOpenfeatureV0ManifestRequest constructs an http.Request for the GetOpenfeatureV0Manifest method
func NewGetOpenfeatureV0ManifestRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/openfeature/v0/manifest")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostOpenfeatureV0ManifestFlagsRequest calls the generic PostOpenfeatureV0ManifestFlags builder with application/json body
func NewPostOpenfeatureV0ManifestFlagsRequest(server string, body PostOpenfeatureV0ManifestFlagsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostOpenfeatureV0ManifestFlagsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostOpenfeatureV0ManifestFlagsRequestWithBody constructs an http.Request for the PostOpenfeatureV0ManifestFlags method, with any body, and a specified content type
func NewPostOpenfeatureV0ManifestFlagsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/openfeature/v0/manifest/flags")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteOpenfeatureV0ManifestFlagsKeyRequest constructs an http.Request for the DeleteOpenfeatureV0ManifestFlagsKey method
func NewDeleteOpenfeatureV0ManifestFlagsKeyRequest(server string, key string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "key", key, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/openfeature/v0/manifest/flags/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutOpenfeatureV0ManifestFlagsKeyRequest calls the generic PutOpenfeatureV0ManifestFlagsKey builder with application/json body
func NewPutOpenfeatureV0ManifestFlagsKeyRequest(server string, key string, body PutOpenfeatureV0ManifestFlagsKeyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutOpenfeatureV0ManifestFlagsKeyRequestWithBody(server, key, "application/json", bodyReader)
}

// NewPutOpenfeatureV0ManifestFlagsKeyRequestWithBody constructs an http.Request for the PutOpenfeatureV0ManifestFlagsKey method, with any body, and a specified content type
func NewPutOpenfeatureV0ManifestFlagsKeyRequestWithBody(server string, key string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "key", key, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/openfeature/v0/manifest/flags/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetOpenfeatureV0ManifestWithResponse Get Project Manifest
	//
	// Returns the project manifest containing active flags. Archived flags are excluded.
	// The response includes an `X-Manifest-Capabilities` header listing token capabilities.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /openfeature/v0/manifest (the `GetOpenfeatureV0Manifest` operationId).
	GetOpenfeatureV0ManifestWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetOpenfeatureV0ManifestResponse, error)

	// PostOpenfeatureV0ManifestFlagsWithBodyWithResponse Create Manifest Flag
	//
	// Creates a new flag exposed through the manifest. The request must be authenticated
	// with a token that includes `write` or `delete` capability. Attempting to create a
	// flag whose key already exists (active or archived) returns 409.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /openfeature/v0/manifest/flags (the `PostOpenfeatureV0ManifestFlags` operationId).
	PostOpenfeatureV0ManifestFlagsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOpenfeatureV0ManifestFlagsResponse, error)

	// PostOpenfeatureV0ManifestFlagsWithResponse Create Manifest Flag
	//
	// Creates a new flag exposed through the manifest. The request must be authenticated
	// with a token that includes `write` or `delete` capability. Attempting to create a
	// flag whose key already exists (active or archived) returns 409.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /openfeature/v0/manifest/flags (the `PostOpenfeatureV0ManifestFlags` operationId).
	PostOpenfeatureV0ManifestFlagsWithResponse(ctx context.Context, body PostOpenfeatureV0ManifestFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOpenfeatureV0ManifestFlagsResponse, error)

	// DeleteOpenfeatureV0ManifestFlagsKeyWithResponse Archive Manifest Flag
	//
	// Removes a flag from the manifest. Providers may implement this as either a soft
	// delete (archive) or a hard delete; consult your provider documentation for specifics.
	// Flags that are active in protected environments may reject deletion requests depending
	// on provider policy.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /openfeature/v0/manifest/flags/{key} (the `DeleteOpenfeatureV0ManifestFlagsKey` operationId).
	DeleteOpenfeatureV0ManifestFlagsKeyWithResponse(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*DeleteOpenfeatureV0ManifestFlagsKeyResponse, error)

	// PutOpenfeatureV0ManifestFlagsKeyWithBodyWithResponse Update Manifest Flag
	//
	// Replaces metadata for an existing manifest flag. The path parameter and body key must
	// match. Archived flags cannot be updated; they must be restored before modification.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /openfeature/v0/manifest/flags/{key} (the `PutOpenfeatureV0ManifestFlagsKey` operationId).
	PutOpenfeatureV0ManifestFlagsKeyWithBodyWithResponse(ctx context.Context, key string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutOpenfeatureV0ManifestFlagsKeyResponse, error)

	// PutOpenfeatureV0ManifestFlagsKeyWithResponse Update Manifest Flag
	//
	// Replaces metadata for an existing manifest flag. The path parameter and body key must
	// match. Archived flags cannot be updated; they must be restored before modification.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /openfeature/v0/manifest/flags/{key} (the `PutOpenfeatureV0ManifestFlagsKey` operationId).
	PutOpenfeatureV0ManifestFlagsKeyWithResponse(ctx context.Context, key string, body PutOpenfeatureV0ManifestFlagsKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*PutOpenfeatureV0ManifestFlagsKeyResponse, error)
}

// GetOpenfeatureV0ManifestResponse200Headers the declared response headers of an HTTP 200 response for GetOpenfeatureV0Manifest
type GetOpenfeatureV0ManifestResponse200Headers struct {
	XManifestCapabilities *string
}

type GetOpenfeatureV0ManifestResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ManifestEnvelope
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *ErrorResponse
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ErrorResponse
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *GetOpenfeatureV0ManifestResponse200Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetOpenfeatureV0ManifestResponse) GetJSON200() *ManifestEnvelope {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetOpenfeatureV0ManifestResponse) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r GetOpenfeatureV0ManifestResponse) GetJSON403() *ErrorResponse {
	return r.JSON403
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetOpenfeatureV0ManifestResponse) GetJSON500() *ErrorResponse {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r GetOpenfeatureV0ManifestResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetOpenfeatureV0ManifestResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOpenfeatureV0ManifestResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetOpenfeatureV0ManifestResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PostOpenfeatureV0ManifestFlagsResponse201Headers the declared response headers of an HTTP 201 response for PostOpenfeatureV0ManifestFlags
type PostOpenfeatureV0ManifestFlagsResponse201Headers struct {
	XManifestCapabilities *string
}

type PostOpenfeatureV0ManifestFlagsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *ManifestFlagResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *ErrorResponse
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *ErrorResponse
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ErrorResponse
	// Headers201 the parsed response headers for an HTTP 201 response
	Headers201 *PostOpenfeatureV0ManifestFlagsResponse201Headers
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r PostOpenfeatureV0ManifestFlagsResponse) GetJSON201() *ManifestFlagResponse {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PostOpenfeatureV0ManifestFlagsResponse) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r PostOpenfeatureV0ManifestFlagsResponse) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r PostOpenfeatureV0ManifestFlagsResponse) GetJSON403() *ErrorResponse {
	return r.JSON403
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r PostOpenfeatureV0ManifestFlagsResponse) GetJSON409() *ErrorResponse {
	return r.JSON409
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r PostOpenfeatureV0ManifestFlagsResponse) GetJSON500() *ErrorResponse {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r PostOpenfeatureV0ManifestFlagsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostOpenfeatureV0ManifestFlagsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostOpenfeatureV0ManifestFlagsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostOpenfeatureV0ManifestFlagsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// DeleteOpenfeatureV0ManifestFlagsKeyResponse200Headers the declared response headers of an HTTP 200 response for DeleteOpenfeatureV0ManifestFlagsKey
type DeleteOpenfeatureV0ManifestFlagsKeyResponse200Headers struct {
	XManifestCapabilities *string
}

type DeleteOpenfeatureV0ManifestFlagsKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ArchiveResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *ErrorResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *ErrorResponse
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *ErrorResponse
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *DeleteOpenfeatureV0ManifestFlagsKeyResponse200Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r DeleteOpenfeatureV0ManifestFlagsKeyResponse) GetJSON200() *ArchiveResponse {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r DeleteOpenfeatureV0ManifestFlagsKeyResponse) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r DeleteOpenfeatureV0ManifestFlagsKeyResponse) GetJSON403() *ErrorResponse {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DeleteOpenfeatureV0ManifestFlagsKeyResponse) GetJSON404() *ErrorResponse {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r DeleteOpenfeatureV0ManifestFlagsKeyResponse) GetJSON409() *ErrorResponse {
	return r.JSON409
}

// GetBody returns the raw response body bytes
func (r DeleteOpenfeatureV0ManifestFlagsKeyResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteOpenfeatureV0ManifestFlagsKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteOpenfeatureV0ManifestFlagsKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteOpenfeatureV0ManifestFlagsKeyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PutOpenfeatureV0ManifestFlagsKeyResponse200Headers the declared response headers of an HTTP 200 response for PutOpenfeatureV0ManifestFlagsKey
type PutOpenfeatureV0ManifestFlagsKeyResponse200Headers struct {
	XManifestCapabilities *string
}

type PutOpenfeatureV0ManifestFlagsKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ManifestFlagResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *ErrorResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *ErrorResponse
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *ErrorResponse
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ErrorResponse
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *PutOpenfeatureV0ManifestFlagsKeyResponse200Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PutOpenfeatureV0ManifestFlagsKeyResponse) GetJSON200() *ManifestFlagResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PutOpenfeatureV0ManifestFlagsKeyResponse) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r PutOpenfeatureV0ManifestFlagsKeyResponse) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r PutOpenfeatureV0ManifestFlagsKeyResponse) GetJSON403() *ErrorResponse {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r PutOpenfeatureV0ManifestFlagsKeyResponse) GetJSON404() *ErrorResponse {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r PutOpenfeatureV0ManifestFlagsKeyResponse) GetJSON409() *ErrorResponse {
	return r.JSON409
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r PutOpenfeatureV0ManifestFlagsKeyResponse) GetJSON500() *ErrorResponse {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r PutOpenfeatureV0ManifestFlagsKeyResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PutOpenfeatureV0ManifestFlagsKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutOpenfeatureV0ManifestFlagsKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PutOpenfeatureV0ManifestFlagsKeyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetOpenfeatureV0ManifestWithResponse Get Project Manifest
//
// Returns the project manifest containing active flags. Archived flags are excluded.
// The response includes an `X-Manifest-Capabilities` header listing token capabilities.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /openfeature/v0/manifest (the `GetOpenfeatureV0Manifest` operationId).
func (c *ClientWithResponses) GetOpenfeatureV0ManifestWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetOpenfeatureV0ManifestResponse, error) {
	rsp, err := c.GetOpenfeatureV0Manifest(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOpenfeatureV0ManifestResponse(rsp)
}

// PostOpenfeatureV0ManifestFlagsWithBodyWithResponse Create Manifest Flag
//
// Creates a new flag exposed through the manifest. The request must be authenticated
// with a token that includes `write` or `delete` capability. Attempting to create a
// flag whose key already exists (active or archived) returns 409.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /openfeature/v0/manifest/flags (the `PostOpenfeatureV0ManifestFlags` operationId).
func (c *ClientWithResponses) PostOpenfeatureV0ManifestFlagsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOpenfeatureV0ManifestFlagsResponse, error) {
	rsp, err := c.PostOpenfeatureV0ManifestFlagsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOpenfeatureV0ManifestFlagsResponse(rsp)
}

// PostOpenfeatureV0ManifestFlagsWithResponse Create Manifest Flag
//
// Creates a new flag exposed through the manifest. The request must be authenticated
// with a token that includes `write` or `delete` capability. Attempting to create a
// flag whose key already exists (active or archived) returns 409.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /openfeature/v0/manifest/flags (the `PostOpenfeatureV0ManifestFlags` operationId).
func (c *ClientWithResponses) PostOpenfeatureV0ManifestFlagsWithResponse(ctx context.Context, body PostOpenfeatureV0ManifestFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOpenfeatureV0ManifestFlagsResponse, error) {
	rsp, err := c.PostOpenfeatureV0ManifestFlags(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOpenfeatureV0ManifestFlagsResponse(rsp)
}

// DeleteOpenfeatureV0ManifestFlagsKeyWithResponse Archive Manifest Flag
//
// Removes a flag from the manifest. Providers may implement this as either a soft
// delete (archive) or a hard delete; consult your provider documentation for specifics.
// Flags that are active in protected environments may reject deletion requests depending
// on provider policy.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /openfeature/v0/manifest/flags/{key} (the `DeleteOpenfeatureV0ManifestFlagsKey` operationId).
func (c *ClientWithResponses) DeleteOpenfeatureV0ManifestFlagsKeyWithResponse(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*DeleteOpenfeatureV0ManifestFlagsKeyResponse, error) {
	rsp, err := c.DeleteOpenfeatureV0ManifestFlagsKey(ctx, key, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteOpenfeatureV0ManifestFlagsKeyResponse(rsp)
}

// PutOpenfeatureV0ManifestFlagsKeyWithBodyWithResponse Update Manifest Flag
//
// Replaces metadata for an existing manifest flag. The path parameter and body key must
// match. Archived flags cannot be updated; they must be restored before modification.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /openfeature/v0/manifest/flags/{key} (the `PutOpenfeatureV0ManifestFlagsKey` operationId).
func (c *ClientWithResponses) PutOpenfeatureV0ManifestFlagsKeyWithBodyWithResponse(ctx context.Context, key string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutOpenfeatureV0ManifestFlagsKeyResponse, error) {
	rsp, err := c.PutOpenfeatureV0ManifestFlagsKeyWithBody(ctx, key, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutOpenfeatureV0ManifestFlagsKeyResponse(rsp)
}

// PutOpenfeatureV0ManifestFlagsKeyWithResponse Update Manifest Flag
//
// Replaces metadata for an existing manifest flag. The path parameter and body key must
// match. Archived flags cannot be updated; they must be restored before modification.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /openfeature/v0/manifest/flags/{key} (the `PutOpenfeatureV0ManifestFlagsKey` operationId).
func (c *ClientWithResponses) PutOpenfeatureV0ManifestFlagsKeyWithResponse(ctx context.Context, key string, body PutOpenfeatureV0ManifestFlagsKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*PutOpenfeatureV0ManifestFlagsKeyResponse, error) {
	rsp, err := c.PutOpenfeatureV0ManifestFlagsKey(ctx, key, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutOpenfeatureV0ManifestFlagsKeyResponse(rsp)
}

// ParseGetOpenfeatureV0ManifestResponse parses an HTTP response from a GetOpenfeatureV0ManifestWithResponse call
func ParseGetOpenfeatureV0ManifestResponse(rsp *http.Response) (*GetOpenfeatureV0ManifestResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOpenfeatureV0ManifestResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ManifestEnvelope
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers GetOpenfeatureV0ManifestResponse200Headers
		if values := rsp.Header.Values("X-Manifest-Capabilities"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Manifest-Capabilities", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XManifestCapabilities = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}

// ParsePostOpenfeatureV0ManifestFlagsResponse parses an HTTP response from a PostOpenfeatureV0ManifestFlagsWithResponse call
func ParsePostOpenfeatureV0ManifestFlagsResponse(rsp *http.Response) (*PostOpenfeatureV0ManifestFlagsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostOpenfeatureV0ManifestFlagsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ManifestFlagResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	switch {
	case rsp.StatusCode == 201:
		var headers PostOpenfeatureV0ManifestFlagsResponse201Headers
		if values := rsp.Header.Values("X-Manifest-Capabilities"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Manifest-Capabilities", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XManifestCapabilities = &value
		}
		response.Headers201 = &headers
	}

	return response, nil
}

// ParseDeleteOpenfeatureV0ManifestFlagsKeyResponse parses an HTTP response from a DeleteOpenfeatureV0ManifestFlagsKeyWithResponse call
func ParseDeleteOpenfeatureV0ManifestFlagsKeyResponse(rsp *http.Response) (*DeleteOpenfeatureV0ManifestFlagsKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteOpenfeatureV0ManifestFlagsKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ArchiveResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers DeleteOpenfeatureV0ManifestFlagsKeyResponse200Headers
		if values := rsp.Header.Values("X-Manifest-Capabilities"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Manifest-Capabilities", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XManifestCapabilities = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}

// ParsePutOpenfeatureV0ManifestFlagsKeyResponse parses an HTTP response from a PutOpenfeatureV0ManifestFlagsKeyWithResponse call
func ParsePutOpenfeatureV0ManifestFlagsKeyResponse(rsp *http.Response) (*PutOpenfeatureV0ManifestFlagsKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutOpenfeatureV0ManifestFlagsKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ManifestFlagResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers PutOpenfeatureV0ManifestFlagsKeyResponse200Headers
		if values := rsp.Header.Values("X-Manifest-Capabilities"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Manifest-Capabilities", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XManifestCapabilities = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}
