name: DCO
on:
  merge_group:
  pull_request:

permissions:  # set top-level default permissions as security best practice
  contents: read # Check https://github.com/ossf/scorecard/blob/7ce8609469289d5f3b1bf5ee3122f42b4e3054fb/docs/checks.md#token-permissions

jobs:
  DCO:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event_name == 'merge_group' }}
        run: echo "skipping DCO check for the merge group"

      ## Allow openfeaturebo skip DCO checks
      - if: ${{ github.event_name == 'pull_request' && github.actor == 'openfeaturebot' }}
        run: echo "skipping DCO for the OpenFeature Bot"